### ISSUE TITLE
Snooping

### ISSUE THREAD

**Issue by cody-greene** [PubbyProject/OrganizerService#7]
I was taking a few minutes to snoop on how people are using my rabbitmq library while I consider how to improve my documentation. I have no idea what this project is about but looking only at the rabbit-related code I feel compelled to write some notes (unsolicited, perhaps completely unwanted) as a way to crystallize my thoughts before I add some of this to the documentation:

https://github.com/PubbyProject/OrganizerService/blob/fb332fcd711fa4d14b4dcb3849dbfa4ff01b63e5/src/services/messaging/rabbitmq_service.ts#L35-L40

Publishers and Consumers are meant to be used as long-lived objects, in the same way as a Connection. Creating a publisher each time you need to send a message is wasteful and slow! Create one Publisher for the lifetime of your application and re-use it, since it can recover from many errors & service interruptions (like rabbitmq restarting).

```javascript
this.con = new Connection()
this.pro = this.con.createPublisher()
// ...
this.pro.publish(...)
```

Similar deal with the Consumer. You're creating a new Consumer each time you call `ConsumeMessage()` but never closing them. You should instead create one long-lived Consumer for the queue. Consumers work asynchronously in that messages are "pushed" to you as an event; the message callback is invoked for any incoming message until the consumer is closed.

However if you really want to "pull" a single message then you can use the low-level api like this:
```javascript
const ch = await connection.acquire()

const msgOrNull = await ch.basicGet({queue: '...'})
if (msgOrNull)
  await ch.basicAck(msgOrNull) // acknowledge receipt

await ch.close()
```

Finally, don't forget to handle application shutdown/restart or the application could stop in the middle of processing an important message.
```javascript
/**
 * Gracefully exit on SIGINT (^c) or SIGTERM
 * Forcefully exit on SIGQUIT (^\)
 * Use this to close any connections or timers so the process can exit
 */
async function onShutdown() {
  await consumer.close() // waits for message handlers to settle
  await publisher.close()
  await connection.close()
  // if there are no other connections or timers the process should now exit
}
process.on('SIGINT', onShutdown)
process.on('SIGTERM', onShutdown)
```

**Comment by calpet** [comment]
Hi Cody,

Thanks for the feedback. I'll improve my publisher/consumer handling next time I'm working on the project & fix the issue(s). I did notice it was a bit slow but it's good to know where exactly the problem lies. As for the context of this project: It's a project I'm doing to learn more about NodeJS/Typescript since I was unfamiliar with the tech stack. I hope my (mis)management of the publisher/consumer objects provided a valuable insight. :)

**Comment by cody-greene** [comment]
:100:
